In [203]:
# Question 1

# f(x) = xSin(3x) - exp(x)

In [204]:
A3 = [0,0]
import matplotlib.pyplot as plt
import numpy as np

In [205]:
# Newton-Raphson method
# Since f(x) = xSin(3x) - exp(x)
# f'(x) = Sin(3x) + 3x*Cos(3x) - exp(x)


x = np.array([-1.6])  # initial guess

for j in range(1000):
    x = np.append(
        x, x[j] - (x[j]*np.sin(3*x[j]) - np.exp(x[j])) 
        / (np.sin(3*x[j]) + 3*x[j]*np.cos(3*x[j]) - np.exp(x[j])))
    fc = x[j]*np.sin(3*x[j]) - np.exp(x[j])

    if abs(fc) < 1e-6:
        break

print(x[j + 1])
print(fc)
A1 = x
A3[0] = len(x) - 1
print(A1)

-0.57078962246829
-6.016180886803113e-09
[-1.6         3.19799514  2.46440244  1.2035359   0.65020146 -0.11692334
 -0.66052349 -0.52192654 -0.56655274 -0.57074658 -0.57078962 -0.57078962]


In [239]:

# bisection method

A2 = []

xr = -0.4; xl = -0.7
for j in range(0, 100):
    xc = (xr + xl)/2
    A2.append(xc)
    fc = xc*(np.sin(3*xc)) - np.exp(xc)   
    if ( fc > 0 ):
        xl = xc   
    else:
        xr = xc
        
    if ( abs(fc) < 1e-6 ):        
        display(xc); display(j)
        A3[1] = len(A2)
        break


print(A3)



-0.5707893371582031

16

[11, 17]


In [245]:
# Question 2
import numpy as np
A = np.array([[1,2],[-1,1]])
B = np.array([[2,0],[0,2]])
C = np.array([[2,0,-3],[0,0,-1]])
D = np.array([[1,2],[2,3],[-1,0]])
x = np.array([1, 0])
y = np.array([0, 1])
z = np.array([1, 2, -1])

"""
np.dot(array a, array b): returns the scalar or dot product of two arrays
np.matmul(array a, array b): returns the matrix product of two arrays
np.multiply(array a, array b): returns the element-wise matrix multiplication of two arrays
"""

#A4
A4 = (np.add(A,B))
print(A4)

[[ 3  2]
 [-1  3]]


In [247]:
#A5
A5 = (np.subtract(np.dot(3,x),np.dot(4,y)))
print(A5)

[ 3 -4]


In [249]:
#A6
A6 = (np.matmul(A,x))
print(A6)

[ 1 -1]


In [251]:
#A7
A7 = (np.matmul(B,np.subtract(x,y)))
print(A7)

[ 2 -2]


In [253]:
#A8
A8 = (np.matmul(D,x))
print(A8)

[ 1  2 -1]


In [255]:
#A9 
A9 = (np.add(np.matmul(D,y),z))
print(A9)

[ 3  5 -1]


In [257]:
#A10 
A10 = (np.matmul(A,B))
print(A10)

[[ 2  4]
 [-2  2]]


In [259]:
#A11
A11 = np.dot(B,C)
print(A11)

[[ 4  0 -6]
 [ 0  0 -2]]


In [263]:
#A12
A12 = np.dot(C,D)
print(A12)

[[5 4]
 [1 0]]
